trigger:
- main

variables:
  azureSubscriptionId: 'ecf79446-5503-4aa3-823a-4bd7ce9ff829'  # Azure subscription ID
  azureTenantId: '3411742b-0e6e-4b8d-b642-44a241f10de3'  # Azure tenant ID
  azureClientId: '4bcac194-e7c2-4979-a43a-95d6c9e1b127'  # Azure client ID
  azureClientSecret: $(azureClientSecret)  # Azure client secret (to be defined as a secret variable)
  azureResourceManagerEndpoint: 'https://management.azure.com/'  # Azure Resource Manager endpoint URL
  azureActiveDirectoryEndpoint: 'https://login.microsoftonline.com'  # Azure Active Directory endpoint URL

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
        displayName: 'Use Python version'

      - script: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install setup
          pip install -r requirements.txt
        workingDirectory: $(System.DefaultWorkingDirectory)
        displayName: "Install requirements"

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        displayName: 'Upload package'
        artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.10'
        displayName: 'Use Python version'

      - script: |
          python -m venv antenv
          source antenv/bin/activate
          python -m pip install --upgrade pip
          pip install setup
          pip install -r requirements.txt
        workingDirectory: $(System.DefaultWorkingDirectory)
        displayName: "Install requirements"

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        displayName: 'Upload package'
        artifact: drop

      - task: AzureWebApp@1
        displayName: 'Deploy Azure Web App : ChicoSeniorPro'
        inputs:
          azureSubscription: $(azureSubscriptionId)
          appName: 'ChicoSeniorPro'
          package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

      - script: |
          az repos create --name "ChicoSeniorPro" --organization "https://dev.azure.com/Rosete" --project "ChicoSeniorPro" --output none
        displayName: 'Create Azure Repo'
