trigger:
- main

variables:
- group: Password
- name: buildConfiguration
  value: 'Release'
- name: GmailPASS
  value: '$(GmailAPP)'

stages:
- stage: PrintGoogleSMTPPassword
  displayName: Print Google SMTP Password
  jobs:
  - job: PrintGoogleSMTPPasswordJob
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          echo 'Google SMTP Password:'
          echo '$(GmailPASS)'
